// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_Myt3w-Tx6jxJfBFwBFjbt_HLb8G_r8',
    appId: '1:911584380054:web:47b9b7d60a422d5930eeb7',
    messagingSenderId: '911584380054',
    projectId: 'realtime-database-esp32-833b9',
    authDomain: 'realtime-database-esp32-833b9.firebaseapp.com',
    databaseURL:
        'https://realtime-database-esp32-833b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-esp32-833b9.firebasestorage.app',
    measurementId: 'G-44DM2Q25HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtbP_XjSZ2zNkFHhX7BJ-8CgZGy6Rz-Vg',
    appId: '1:911584380054:android:57f5ad163ce5e95130eeb7',
    messagingSenderId: '911584380054',
    projectId: 'realtime-database-esp32-833b9',
    databaseURL:
        'https://realtime-database-esp32-833b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-esp32-833b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfhnmfh3130ahSeSfW8SU-TQ0X_cARhHY',
    appId: '1:911584380054:ios:f288d36b63774dda30eeb7',
    messagingSenderId: '911584380054',
    projectId: 'realtime-database-esp32-833b9',
    databaseURL:
        'https://realtime-database-esp32-833b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-esp32-833b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfhnmfh3130ahSeSfW8SU-TQ0X_cARhHY',
    appId: '1:911584380054:ios:f288d36b63774dda30eeb7',
    messagingSenderId: '911584380054',
    projectId: 'realtime-database-esp32-833b9',
    databaseURL:
        'https://realtime-database-esp32-833b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-esp32-833b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_Myt3w-Tx6jxJfBFwBFjbt_HLb8G_r8',
    appId: '1:911584380054:web:0f4f987fc07d6a5c30eeb7',
    messagingSenderId: '911584380054',
    projectId: 'realtime-database-esp32-833b9',
    authDomain: 'realtime-database-esp32-833b9.firebaseapp.com',
    databaseURL:
        'https://realtime-database-esp32-833b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-esp32-833b9.firebasestorage.app',
    measurementId: 'G-DZ7SJHBG7T',
  );
}
